### ISSUE TITLE
Finding global generators on io.js

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/environment#30]
For some reason global generator cannot be found on io.js - this also cause a test failure on Travis when using io.js.

Note: I have **not** reproduce this myself of a system, I need to investigate and reproduce. We know we have a test failure. That doesn't mean it is not working.

**Comment by whitlockjc** [comment]
I've started looking into this.  I'll report my findings.

**Comment by whitlockjc** [comment]
Whenever using io.js, if I run `yo doctor`, I get the following:

```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory

Everything looks all right!
```

Now, one problem I did run into before this was about an invalid `NODE_PATH` being set but it had nothing to do with io.js and was a relic of my pre-nvm days.  _(To fix it, I actually unset `NODE_PATH` and let nvm do the right thing.)_  I will now clone the sources of yeoman and run the test suite.

**Comment by whitlockjc** [comment]
If you know of a more specific path to reproducing the issue, let me know.

**Comment by SBoudrias** [comment]
Running the test suite and fixing the test on io.js would be a great first step - and might actually just fix the issue

**Comment by whitlockjc** [comment]
Sounds like I'm on the right track then.  I am running into an issue with running `npm test` where I get a `422` from coveralls.  I'm looking into it but I don't see anything documented in the project.  Here is the error: `Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}`  If this makes sense, let me know.  Otherwise, I'm already on the hunt.

**Comment by whitlockjc** [comment]
Tests run fine locally for me.  I see that `.travis.yml` uses `before_script` to set `NODE_PATH` and that was causing me issues when initially installing `yo` for io.js so I'll see if I can reproduce the issue I ran into locally with `NODE_PATH` on Travis-CI.

**Comment by whitlockjc** [comment]
So, I can reproduce this and it appears to be only on Travis.  If I run the tests locally (OS X with io.js), everything runs fine.  When I submit the project to Travis-CI, it fails and I think it's due to this: [creationix/nvm/issues/586](https://github.com/creationix/nvm/issues/586).  If I comment out/remove the `before_script` from `.travis.yml` where `NODE_PATH` is being set, all tests pass locally and on Travis-CI.

**Comment by whitlockjc** [comment]
I guess we can remove this since it doesn't seem to be required or we can have `NODE_PATH` set properly, if possible _(I'm not saying it isn't possible, just saying I've not looked into it enough to see the best way to do this.)_.  Those seem to be the options.

**Comment by SBoudrias** [comment]
What is different with the `before_script` between node.js setup and iojs? It didn't caused issue before.

**Comment by whitlockjc** [comment]
Node.js works with `before_script` but Io.js does not.  The issue I linked to above seems to talk about the issue in greater detail but it seems with nvm+io.js, `NODE_PATH` either needs to be set differently or not set at all.  I ran into this same issue locally when installing yeoman and that's where I got the idea to test this out.

**Comment by whitlockjc** [comment]
If you want/need to use `NODE_PATH`, which I'm not sure you do because removing it seems to have tests pass just fine for io.js and node.js, it probably just needs to be set to something like this:

```
NODE_PATH=`npm root -g`
```

Using that, I can get `yo doctor` to run fine locally even whereas before it would complain.

**Comment by whitlockjc** [comment]
Maybe Travis-CI doesn't set `NVM_PATH` properly.  What you have in `before_script` for `NODE_PATH` works locally for me.  So it seems this issue is specific to Travis-CI.  It's up to you how we fix it, I don't mind doing the work if you can let me know which approach you want to be taken:

* Remove `before_script` as it doesn't seem to be required
* Update `before_script` to set `NODE_PATH` where it works locally and on Travis-CI

**Comment by SBoudrias** [comment]
@whitlockjc I think not setting it is disabling a test (changing `it` to `xit`). Can you verify?

If it doesn't, well then I'm fine with removing it.

**Comment by whitlockjc** [comment]
You got it.  If it is, I will get started on a PR to have it set properly.

**Comment by whitlockjc** [comment]
You are right, I didn't know about that.  Here is the reference for those following along at home: [test/resolver.js#L8](https://github.com/yeoman/environment/blob/59170aa1d3a0297bf13c5ae4f0001915edbc0e2f/test/resolver.js#L8).  I will adjust my plan accordingly.

**Comment by whitlockjc** [comment]
So, I was terribly wrong.  I apologize.  Now that I know about the above test being skipped when `NODE_PATH` was not set, I am now able to reproduce this.  Please forgive me.  I'll get it sorted and the PR should be a real fix and nothing related to `NODE_PATH`.  Thanks for your patience, I'm new to the code base.

**Comment by whitlockjc** [comment]
I removed the comments above _(that were mine)_ as they were misleading.  Now that I know the importance of `NODE_PATH` to the test suite, I didn't want someone reading this and making the same mistake I did.  I'll be away for a bit but I'll be back later to get you a PR.  Sorry for deleting comments, I wouldn't usually do it but this time I think they caused more confusion than anything.

**Comment by whitlockjc** [comment]
Figured it out.  :)  I'll get you a PR shortly.

**Comment by whitlockjc** [comment]
This is not an io.js issue.  Basically, any generator path with more than one `.js` in it will create this issue.
