### ISSUE TITLE
Hangs in my CI environment, after 3.0.0 and upwards

### ISSUE THREAD

**Issue by wbern** [yeoman/environment#315]
Hey!

It seems like when I do `helpers.run(...)`, the process simply hangs and never starts any generators.

When I revert to 2.10.3, it works.

It's really hard for me to reproduce this because I have no issues running locally. Jenkins CI is running node 14.15.4, same as what I have locally.

Jenkins is also running in a docker container.

**Comment by wbern** [comment]
This is still an issue.

**Comment by breglerj** [comment]
I think the issue is somehow related to the generator namespace. I fixed it by explicitly defining a namespace for the generator I was trying to test:

```
helpers.run( require( 'generators/app' ), { resolved: path.join( __dirname, 'generators/app' ), namespace: '@my/custom-generator:app' })
```

In addition I was using a sub-generator in the same project. The sub-generator didn't have the `generator-` prefix which wasn't an issue with version 2 of yeoman-environment. However, version 3 seems to require that all generator names start with the `generator-` prefix to be able to correctly resolve them.

**Comment by sclarkson-zoomcare** [comment]
@breglerj we were having the exact same issue with Jenkins, and your suggestion resolved it. Thank you!

### Dependencies
```shell
├─ yeoman-assert@3.1.1
├─ yeoman-environment@3.9.1
├─ yeoman-generator@5.6.1
└─ yeoman-test@6.3.0
└─ mocha@10.0.0
```

Running Jenkins 2.366
