### ISSUE TITLE
Sub-sub-generators

### ISSUE THREAD

**Issue by pauldijou** [yeoman/environment#39]
When reading some code or doc, I came across stuff like `yo name:sub:more` (cf [here](https://github.com/yeoman/environment/blob/0af43f7c5b67cb2190f478b19eb7eba91dfb3d56/lib/environment.js#L211-L215)), but reading some other code source, it looks like it will never be able to handle such a sub-sub-generator (see [here](https://github.com/yeoman/environment/blob/master/lib/resolver.js#L19)) but I'm not 100% sure...

So... is there a way to handle sub-sub-generators? Is there a meaning to do something like `yo angular:common:all`? If not, would it be a good idea to consider supporting deeper level of sub-generators?

**Comment by twixie** [comment]
In my humble opinion, this isn't really needed. `gen:sub:sub` seems like not really friendly to the user anymore.

**Comment by SBoudrias** [comment]
Hey, sorry for the very late answer. But to explain, the getter/namespace logic can handle any nested level of "generators". That being said, this capacity is not reflected into the app because it is not used when resolving generators installed on your machine.

FWIW, that logic is present in the getter/namespace logic mainly because of the aliases (`node:app === node`). There might be other historic reason that I don't know about - but these reason wouldn't be affecting the app today.

On a related note, I will probably clean up that alias logic as part of #48

**Comment by eh-am** [comment]
So sub-sub-generators aren't available anymore? :(

**Comment by SBoudrias** [comment]
@eh-am Actually, they never were available.

**Comment by aallbrig** [comment]
Too bad. I was thinking about categorizing different generators to keep each individual generator as single purpose as possible for an repo specific yeoman generator. My sub generator folder is starting to _feel_ like a sock drawer.

e.g.
```
${my-generator-name}:app-code:${name-of-specific-type-of-app-code}
${my-generator-name}:infrastructure:${name-of-specific-type-of-app-code}
${my-generator-name}:text-templates:${name-of-specific-text-template}
```

The idea is that my top level sub generators represent only a manageable handful of categories. A graph tree depth of 2 (sub sub generators) provides more options than 1 (sub generators).

All that said, there's another way to achieve the kind of composability I like with the organization of code. E.g. each top level sub generator above becomes a new yeoman generator.

Hope this thinking helps the next yeoman engineer following the same sort of thought process :)
